---
title: Defense Acquisition Trends 
output: 
  flexdashboard::flex_dashboard:
    # logo: GSF_logo_2016_RGB2.jpg
    theme: lumen 
    social: menu
   
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
```

DoD Overall 
=======================================================================

```{r echo = FALSE}

shinyAppFile("1b.R", options=list(width="100%", height=840))


```

Army | Navy | Air Force  
=======================================================================

```{r echo = FALSE}


shinyAppFile("6b.R", options=list(width="100%", height=840))


```

Platform Portfolio 
=======================================================================

```{r echo = FALSE}


shinyAppFile("5b.R", options=list(width="100%", height=840))


```


Vendor Size  
=======================================================================

```{r echo = FALSE}


shinyAppFile("2b.R", options=list(width="100%", height=840))


```

Customer  
=======================================================================

```{r echo = FALSE}


shinyAppFile("3b.R", options=list(width="100%", height=840))


```

Area 
=======================================================================

```{r echo = FALSE}


shinyAppFile("4b.R", options=list(width="100%", height=840))


```

Contract Type
=======================================================================

```{r echo = FALSE}


shinyAppFile("8b.R", options=list(width="100%", height=840))


```

Competition Level
=======================================================================

```{r echo = FALSE}


shinyAppFile("7b.R", options=list(width="100%", height=840))


```