---
title: 
output: 
  flexdashboard::flex_dashboard:
    logo: logo 5.png
    theme: lumen 
    social: menu
   
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
```

$ Breakdown 
=======================================================================

```{r echo = FALSE}

shinyAppFile("1.R", options=list(width="100%", height=840))


```

$ by Service 
=======================================================================

```{r echo = FALSE}


shinyAppFile("6a.R", options=list(width="100%", height=840))


```

$ by Platform 
=======================================================================

```{r echo = FALSE}


shinyAppFile("5a.R", options=list(width="100%", height=840))


```


Share by Vendor Size 
=======================================================================

```{r echo = FALSE}


shinyAppFile("2.R", options=list(width="100%", height=840))


```

Share by Customer  
=======================================================================

```{r echo = FALSE}


shinyAppFile("3.R", options=list(width="100%", height=840))


```

Share by Area  
=======================================================================

```{r echo = FALSE}


shinyAppFile("4.R", options=list(width="100%", height=840))


```

The CSIS Methodology 
=======================================================================

